version: "3.7"
services:
        nginx:
               image: nginx:latest
               container_name: nginx_production
               ports:
                       - "80:80"
               volumes:
                       - .:/django
                       - ./config/nginx/:/etc/nginx/conf.d
                       - ./static:/static
               depends_on:
                       - prod

        prod:
               container_name: django-production
               build:
                       context: .
                       dockerfile: Dockerfile
               env_file: .env
               command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
               volumes:
                       - .:/django/
               ports:
                       - "8000:8000"
